from typing import TypedDict, List

class PRState(TypedDict, total=False):
    # Input fields (required to start graph)
    diff: str
    commits: str

    # Generated by agent
    summary: str
    risks: List[str]
    missing_tests: List[str]
    score: int